name: agar_online
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.3+17

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0+2
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  lottie: ^1.4.2
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5+3
  http_parser: ^4.0.1
  carousel_slider: ^4.1.1

  # DI & State management
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1

  # Network
  dartz: ^0.10.1
  pretty_dio_logger: ^1.2.0-beta-1
  dio: ^4.0.6
  connectivity_plus: ^2.3.6+1
  url_launcher: ^6.1.5
  share_plus: ^4.1.0

  # storage
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^6.0.0

  # firebase
  firebase_core: ^1.22.0
  firebase_messaging: ^13.1.0
  flutter_local_notifications: ^12.0.2

  # social auth
  google_sign_in: ^5.4.1
  flutter_facebook_auth: ^4.4.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # flutter_launcher_icons: ^0.9.3

# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/images/app_logo.jpeg"


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/arabic/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/arabic/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/arabic/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/arabic/Tajawal-Light.ttf
          weight: 300
    - family: Poppins
      fonts:
        - asset: assets/fonts/english/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/english/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/english/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/english/Poppins-Light.ttf
          weight: 300